### ISSUE TITLE
Can't add private comments to appeals (was: RealMediaWiki error)

### ISSUE THREAD

**Issue by dqwiki** [UTRS2/utrs#394]
"class": "TypeError",
    "message": "Argument 1 passed to App\\Services\\MediaWiki\\Implementation\\RealMediaWikiRepository::getWikiPermissionHandler() must be of the type string, null given, called in /var/www/beta/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 261",
    "code": 0,
    "file": "/var/www/beta/app/Services/MediaWiki/Implementation/RealMediaWikiRepository.php:80"

**Comment by supertassu** [comment]
I need the full stack trace

**Comment by supertassu** [comment]
this is happening when you attempt to add a private comment to an appeal. relevant parts of the stack trace are below:

```
[2020-12-12 12:34:45] local.ERROR: Argument 1 passed to App\Services\MediaWiki\Implementation\RealMediaWikiRepository::getWikiPermissionHandler() must be of the type string, null given, called in C:\Users\taavi\sites\utrs\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 261 {"userId":2,"exception":"[object] (TypeError(code: 0): Argument 1 passed to App\\Services\\MediaWiki\\Implementation\\RealMediaWikiRepository::getWikiPermissionHandler() must be of the type string, null given, called in C:\\Users\\taavi\\sites\\utrs\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php on line 261 at C:\\Users\\taavi\\sites\\utrs\\app\\Services\\MediaWiki\\Implementation\\RealMediaWikiRepository.php:80)
[stacktrace]
#0 C:\\Users\\taavi\\sites\\utrs\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(261): App\\Services\\MediaWiki\\Implementation\\RealMediaWikiRepository->getWikiPermissionHandler(NULL)
#1 C:\\Users\\taavi\\sites\\utrs\\app\\Policies\\AppealPolicy.php(36): Illuminate\\Support\\Facades\\Facade::__callStatic('getWikiPermissi...', Array)
#2 C:\\Users\\taavi\\sites\\utrs\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Access\\Gate.php(719): App\\Policies\\AppealPolicy->view(Object(App\\Models\\User), Object(App\\Models\\Appeal))
#3 C:\\Users\\taavi\\sites\\utrs\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Access\\Gate.php(672): Illuminate\\Auth\\Access\\Gate->callPolicyMethod(Object(App\\Policies\\AppealPolicy), 'view', Object(App\\Models\\User), Array)
#4 C:\\Users\\taavi\\sites\\utrs\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Access\\Gate.php(474): Illuminate\\Auth\\Access\\Gate->Illuminate\\Auth\\Access\\{closure}(Object(App\\Models\\User), Object(App\\Models\\Appeal))
#5 C:\\Users\\taavi\\sites\\utrs\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Access\\Gate.php(371): Illuminate\\Auth\\Access\\Gate->callAuthCallback(Object(App\\Models\\User), 'view', Array)
#6 C:\\Users\\taavi\\sites\\utrs\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Access\\Gate.php(336): Illuminate\\Auth\\Access\\Gate->raw('view', Array)
#7 C:\\Users\\taavi\\sites\\utrs\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Access\\Gate.php(323): Illuminate\\Auth\\Access\\Gate->inspect('view', Object(App\\Models\\Appeal))
#8 C:\\Users\\taavi\\sites\\utrs\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(261): Illuminate\\Auth\\Access\\Gate->authorize('view', Object(App\\Models\\Appeal))
#9 C:\\Users\\taavi\\sites\\utrs\\app\\Policies\\AppealPolicy.php(76): Illuminate\\Support\\Facades\\Facade::__callStatic('authorize', Array)
#10 C:\\Users\\taavi\\sites\\utrs\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Access\\Gate.php(719): App\\Policies\\AppealPolicy->update(Object(App\\Models\\User), Object(App\\Models\\Appeal))
#11 C:\\Users\\taavi\\sites\\utrs\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Access\\Gate.php(672): Illuminate\\Auth\\Access\\Gate->callPolicyMethod(Object(App\\Policies\\AppealPolicy), 'update', Object(App\\Models\\User), Array)
#12 C:\\Users\\taavi\\sites\\utrs\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Access\\Gate.php(474): Illuminate\\Auth\\Access\\Gate->Illuminate\\Auth\\Access\\{closure}(Object(App\\Models\\User), Object(App\\Models\\Appeal))
#13 C:\\Users\\taavi\\sites\\utrs\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Access\\Gate.php(371): Illuminate\\Auth\\Access\\Gate->callAuthCallback(Object(App\\Models\\User), 'update', Array)
#14 C:\\Users\\taavi\\sites\\utrs\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Access\\Gate.php(336): Illuminate\\Auth\\Access\\Gate->raw('update', Array)
#15 C:\\Users\\taavi\\sites\\utrs\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Access\\Gate.php(323): Illuminate\\Auth\\Access\\Gate->inspect('update', Object(App\\Models\\Appeal))
#16 C:\\Users\\taavi\\sites\\utrs\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Auth\\Access\\AuthorizesRequests.php(23): Illuminate\\Auth\\Access\\Gate->authorize('update', Object(App\\Models\\Appeal))
#17 C:\\Users\\taavi\\sites\\utrs\\app\\Http\\Controllers\\AppealController.php(291): App\\Http\\Controllers\\Controller->authorize('update', Object(App\\Models\\Appeal))
#18 C:\\Users\\taavi\\sites\\utrs\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): App\\Http\\Controllers\\AppealController->comment(Object(Illuminate\\Http\\Request), Object(App\\Models\\Appeal), '2')
```
